name: Test
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        llvm: [10.0.1, 11.0.1]
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          version: ${{ matrix.llvm }}
      - run: command llvm-config --version
      - run: llvm-config --version | grep -q '${{ matrix.llvm }}'
